// Generated by CoffeeScript 1.6.1
(function() {
  var hallo;

  hallo = angular.module("hallo", []);

  hallo.directive("hallo", function() {
    var directive;
    directive = {
      restrict: 'A',
      require: 'ngModel',
      link: function(scope, elm, attrs, ngModel) {
        elm.hallo;
        return elm.on("hallomodified", function() {
          return ngModel.$setViewValue(elm.html());
        });
      }
    };
    return directive;
  });

}).call(this);
